version: '3'
services:
  eureka:
    image: jiglesgom/eureka
    ports:
      - "8761:8761"
  zuul:
    image: jiglesgom/zuul
    ports:
      - "8765:8765"
  hystrix-dashboard:
    image: jiglesgom/hystrix-dashboard
    ports:
      - "7979:7979"
  hello:
    image: jiglesgom/hello
    ports:
      - "8762:8762"