server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/,http://localhost:8761/eureka,http://jig-eureka.io.d.ip6n.net:8761/eureka

spring:
  application:
    name: headers